# ── ADB Info ───────────────────────────────────────────────────────────────────

output "adb_id" {
  description = "OCID of the Autonomous Database"
  value       = oci_database_autonomous_database.adb.id
}

output "adb_state" {
  description = "Lifecycle state of the ADB (should be AVAILABLE before connecting)"
  value       = oci_database_autonomous_database.adb.state
}

output "adb_display_name" {
  description = "Display name of the ADB"
  value       = oci_database_autonomous_database.adb.display_name
}

# ── MongoDB API Connection ──────────────────────────────────────────────────────

output "mongodb_api_host" {
  description = "Hostname for the MongoDB-compatible API endpoint"
  value       = local.adb_mongo_host
}

output "mongodb_api_port" {
  description = "Port for the MongoDB-compatible API (always 27017 on OCI ADB)"
  value       = 27017
}

output "mongo_uri_template" {
  description = <<-EOT
    MONGO_URI template for the NestJS .env file.
    Replace $MONGO_PASSWORD with the actual password (var.adb_mongo_password).
    Use the sensitive output 'mongo_uri_full' to get the password-embedded URI.
  EOT
  value = local.mongo_uri
}

output "mongo_uri_full" {
  description = "Full MONGO_URI with embedded password — treat as a secret."
  value       = local.mongo_uri_with_password
  sensitive   = true
}

# ── NestJS .env snippet ────────────────────────────────────────────────────────

output "nestjs_env_snippet" {
  description = <<-EOT
    Paste this block into the NestJS app .env file (or set as env vars).
    Retrieve the full MONGO_URI with: terraform output -raw mongo_uri_full
  EOT
  value = <<-ENV
    # .env — generated by Terraform (mongoOracleInfra)
    NODE_ENV=development
    PORT=3000

    MONGO_URI=<run: terraform output -raw mongo_uri_full>
    MONGO_DB_NAME=${var.adb_mongo_username}
  ENV
}

# ── Manual user-creation SQL ───────────────────────────────────────────────────
# Use this if the null_resource provisioner could not run (no OCI CLI / sqlplus).

output "manual_user_sql" {
  description = <<-EOT
    SQL to run as ADMIN in SQL Worksheet (OCI Console → Database Actions)
    if the automatic user-creation step was skipped.
  EOT
  value = <<-SQL
    -- Run as ADMIN in SQL Worksheet
    CREATE USER "${upper(var.adb_mongo_username)}" IDENTIFIED BY "<your_mongo_password>";
    GRANT CREATE SESSION TO "${upper(var.adb_mongo_username)}";
    GRANT SODA_APP        TO "${upper(var.adb_mongo_username)}";
    GRANT CREATE TABLE    TO "${upper(var.adb_mongo_username)}";
    GRANT CREATE SEQUENCE TO "${upper(var.adb_mongo_username)}";
    GRANT CREATE VIEW     TO "${upper(var.adb_mongo_username)}";
    ALTER USER "${upper(var.adb_mongo_username)}" QUOTA UNLIMITED ON DATA;
    COMMIT;

    -- Enable ORDS/MongoDB API access for the schema (required for MongoDB wire protocol)
    BEGIN
      ORDS.ENABLE_SCHEMA(
        p_enabled             => TRUE,
        p_schema              => '${upper(var.adb_mongo_username)}',
        p_url_mapping_type    => 'BASE_PATH',
        p_url_mapping_pattern => '${lower(var.adb_mongo_username)}',
        p_auto_rest_auth      => TRUE
      );
      COMMIT;
    END;
    /
  SQL
}
